apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  namespace: team5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-api
  template:
    metadata:
      labels:
        app: hello-api
    spec:
      containers:
      - name: hello-api
        image: k8s-vga-master:5000/hello-api:1.0
        ports:
        - containerPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-api-service
  namespace: team5
spec:
  selector:
    app: hello-api
  ports:
  - protocol: TCP
    port: 18080
    targetPort: 18080
  type: NodePort